version: '3.5'

services:
  demo-app:
    image: app
    build:
      context: .
      dockerfile: deploy/app/Dockerfile
    container_name: demo_app
    networks:
      - demo
    ports:
      - 8090:8090
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongo_db
    hostname: mongo
    networks:
      - demo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITBD_DATABASE: demo-db
    volumes:
      - .data:/data/db
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    networks:
      - demo
    ports:
      - 8071:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo

volumes:
  data:

networks:
  demo: